version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14
    working_directory: ~/repo/backend
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "backend/package.json" }}
            - v1-dependencies-
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "backend/package.json" }}


workflows:
  version: 2
  build_and_test:
    jobs:
      - build
